POST http://localhost:8000/funql HTTP/1.1
content-type: application/json
token:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzMzMzY0MDMuMzYzLCJ1c2Vyc0lkIjoiNjA2ZDZmNDBjNDAwZGY5YzlkNDU4ZjI5In0.Erl-YOCWtlEfIJx5CwQr1INK4zm9d8rAGBfTyQeFrTVJhAbboIdbN8jghTops64lmO6_rq7Npyf9FqCjwa9HmQ

{
    
    "wants":{
        "model":"BlogPost",
        "doit":"popularPosts"
    }
}