
POST http://localhost:8000/funql HTTP/1.1
content-type: application/json

{
    "contents":"dynamic",
    "details":{
    "set":{},
        "get":{
            "name":1,
            "lastName":1,
            "phone":1

            }
        
    },
    "wants":{
        "model":"User",
        "doit":"getMe"
    }
}
