POST http://localhost:8000/funql HTTP/1.1
content-type: application/json
# //normalUser token
# token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzMzMzY0MDMuMzYzLCJ1c2Vyc0lkIjoiNjA2ZDRkODIyN2MwMDM1YWU1OTc0ODJlIn0.NK3NX2EKxA6R36Ek1kkKpl6wkUwsxySmwLesNaJvuEqKWrkj0dc3S8U4BkuXZMDUbDYa6aI79UBp4VAHst0SIg
#//admin Token 

{
    "contents":"dynamic",
    "details": {
        "get": {
            "_id":1,
            "name": 1,
            "enName":1,
                "country":{

                    "name":1
                } 
           
        },
        "set":{
"countryId":"6152bc9e4ea689b8e8ff34e6",
           "sort":{
             
           },
           "pagination":{
           "page":1,
           "limit":25
           }

        }
    },
    "wants": {
        "model": "State",
        "doit": "getStates"
    }
}
